spring:
  datasource:
    url: jdbc:mysql://root:NncPbTCUjVkiuKNADoMiHiPWLZgwrXyj@mysql-ovwg.railway.internal:3306/railway
    username: root
    password: NncPbTCUjVkiuKNADoMiHiPWLZgwrXyj
  jpa:
    hibernate:
      ddl-auto: create
