spring:
  datasource:
    url: jdbc:mysql://root:BWDddDLzTFHTPJAYXyPszYFVqzXjmtPl@mysql.railway.internal:3306/railway
    username: root
    password: BWDddDLzTFHTPJAYXyPszYFVqzXjmtPl
  jpa:
    hibernate:
      ddl-auto: create